version: '2'
services:
  bungee:
    # image: bungee-ecs
    image: 033441544097.dkr.ecr.us-east-1.amazonaws.com/bungee-ecs
    container_name: bungee
    ports: 
      - 25577:25577
    links: 
      - minecraft

  minecraft:
    # image: minecraft-ecs
    image: 033441544097.dkr.ecr.us-east-1.amazonaws.com/minecraft-ecs
    container_name: minecraft-hub
    ports: 
      - 25565:25565
      - 25575:25575
    environment:
      - EULA=true
      - TYPE=SPIGOT
      - ENABLE_RCON=true
      - RCON_PASSWORD=testing
      - RCON_PORT=25575
      - ENABLE_QUERY=true
      - QUERY_PORT=25565
      - MODE=creative
      - FORCE_GAMEMODE=true
      - MOTD="Vanilla test server in a docker container."
      - ONLINE_MODE=false
      - OPS=jdrivas

  minecraft-01:
    # image: minecraft-ecs
    image: 033441544097.dkr.ecr.us-east-1.amazonaws.com/minecraft-ecs
    container_name: minecraft-01
    ports: 
      - 35566:25565
      # - 25575:25575
    environment:
      - EULA=true
      - TYPE=SPIGOT
      - ENABLE_RCON=true
      - RCON_PASSWORD=testing
      - RCON_PORT=25575
      - ENABLE_QUERY=true
      - QUERY_PORT=25565
      - MODE=creative
      - FORCE_GAMEMODE=true
      - MOTD="Vanilla test server in a docker container."
      - ONLINE_MODE=false
      - OPS=jdrivas

  minecraft-02:
    # image: minecraft-ecs
    image: 033441544097.dkr.ecr.us-east-1.amazonaws.com/minecraft-ecs
    container_name: minecraft-02
    ports: 
      - 35567:25565
      # - 25575:25575
    environment:
      - EULA=true
      - TYPE=SPIGOT
      - ENABLE_RCON=true
      - RCON_PASSWORD=testing
      - RCON_PORT=25575
      - ENABLE_QUERY=true
      - QUERY_PORT=25565
      - MODE=creative
      - FORCE_GAMEMODE=true
      - MOTD="Vanilla test server in a docker container."
      - ONLINE_MODE=false
      - OPS=jdrivas
